apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-query-app
  labels:
    app: time-query-app
spec:
  replicas: 1
  template:
    metadata:
      name: time-query-app
      labels:
        app: time-query-app
    spec:
      containers:
        - name: time-query-app
          image: lnanjangud653/curr-time:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: time-query-app
---
apiVersion: v1
kind: Service
metadata:
  name: time-query-app
spec:
  selector:
    app: time-query-app
  ports:
    - port: 80
      targetPort: 8888
  type: LoadBalancer
